name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/monkas-github-gcc:v1@sha256:2ec74a0e76a11fb384c86fe60e06f2ff789d6e7442ba8d9a4307a0e3750a43bb
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check clang-format
        run: |
          find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format --dry-run --Werror {} +

  build_release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/monkas-github-gcc:v1@sha256:2ec74a0e76a11fb384c86fe60e06f2ff789d6e7442ba8d9a4307a0e3750a43bb
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: CMake Release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -B build -S .
          cmake --build build --config Release

  build_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/monkas-github-gcc:v1@sha256:2ec74a0e76a11fb384c86fe60e06f2ff789d6e7442ba8d9a4307a0e3750a43bb
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: CMake Debug build with sanitizers
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -D CMAKE_C_FLAGS="-fno-omit-frame-pointer -fsanitize=address,undefined" -D CMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address,undefined" -G Ninja -B build -S .
          cmake --build build --config Debug

      - name: Run tests
        run: |
          cd build && ctest --no-tests=error --verbose

      - name: CLI example help
        run: |
          ./build/examples/cli/monka --help || true

      - name: CLI example nerdstats/dumppackets
        run: |
          timeout --preserve-status 1 ./build/examples/cli/monka -nerdstats -dumppackets || true
