name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    container:
      image: gcc@sha256:a4da41bd17f92a512d2e59f3272ae6315fd01ff4857875f8b6c7dac207410ead
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install clang-format
        run: |
          apt-get update --yes
          apt-get install --yes clang-format

      - name: Check clang-format
        run: |
          find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format --dry-run --Werror {} +

  build_release:
    runs-on: ubuntu-latest
    container:
      image: gcc@sha256:a4da41bd17f92a512d2e59f3272ae6315fd01ff4857875f8b6c7dac207410ead
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install dependencies
        run: |
          apt-get update --yes
          apt-get install --yes cmake libmnl-dev libspdlog-dev libgflags-dev ninja-build libasan6 libubsan1

      - name: CMake Release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -B build -S .
          cmake --build build --config Release

  build_test:
    runs-on: ubuntu-latest
    container:
      image: gcc@sha256:a4da41bd17f92a512d2e59f3272ae6315fd01ff4857875f8b6c7dac207410ead
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install dependencies
        run: |
          apt-get update --yes
          apt-get install --yes cmake libmnl-dev libspdlog-dev libgflags-dev ninja-build libasan6 libubsan1

      - name: CMake Debug build with sanitizers
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -D CMAKE_C_FLAGS="-fno-omit-frame-pointer -fsanitize=address,undefined" -D CMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address,undefined" -G Ninja -B build -S .
          cmake --build build --config Debug

      - name: Run tests
        run: |
          cd build && ctest --no-tests=error --verbose

      - name: CLI example help
        run: |
          ./build/examples/cli/monka --help || true

      - name: CLI example nerdstats/dumppackets
        run: |
          timeout --preserve-status 1 ./build/examples/cli/monka -nerdstats -dumppackets || true
